version: '3.9' 
volumes:
  app_media: {}
  db_data: {}
services:
  web:
    image: nginx:alpine
    restart: always
    labels:
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=20971520
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=20971520
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=20971520
      - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=20971520
      - traefik.http.routers.${TRAEFIK_ROUTE}.rule=Host(${TRAEFIK_APP_DOMAIN})
      - traefik.http.routers.${TRAEFIK_ROUTE}.tls=true
      - traefik.http.routers.${TRAEFIK_ROUTE}.tls.certresolver=lets-encrypt
      - traefik.port=${TRAEFIK_APP_PORT}
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - app_media:/app/media
    depends_on:
      - app
    networks:
      - web
      - internal  
  app:
    image: gcr.io/jevillanueva/pythonlapaz/pyday:latest
    restart: always
    expose:
      - "8000"
    volumes:
      - app_media:/app/media
    env_file:
      - backend/.env
    depends_on:
      - database
    networks:
      - internal
  database:
    image: liupeng0518/mysql:8.0-arm64
    restart: always
    env_file:
      - database/.env
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
networks:
  web:
    external: true
  internal:
    external: false
