# Generated by Django 4.1.7 on 2023-02-18 23:31

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="event",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="literal_date",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="location",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="url_get_tickets",
            field=models.URLField(blank=True),
        ),
    ]
