# Generated by Django 4.1.7 on 2023-02-21 20:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0004_homepage_hero_image_homepage_logo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "list_options",
                    wagtail.fields.StreamField(
                        [
                            (
                                "options",
                                wagtail.blocks.StructBlock(
                                    [("name", wagtail.blocks.CharBlock())]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=None,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "position",
                    models.CharField(
                        choices=[("left", "Izquierda"), ("right", "Derecha")],
                        default="left",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
