# Generated by Django 4.1.7 on 2023-02-21 20:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_segmentpage_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentpage",
            name="segments",
            field=wagtail.fields.StreamField(
                [
                    (
                        "options",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "list_options",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.CharBlock()
                                    ),
                                ),
                                ("url", wagtail.blocks.URLBlock(blank=True)),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "position",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Izquierda"),
                                            ("right", "Derecha"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=False,
            ),
        ),
    ]
