# Generated by Django 4.1.7 on 2023-02-22 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0019_homepage_footer_networks_homepage_footer_site_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="logo_image_big",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
