# Generated by Django 4.1.7 on 2023-02-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_homepage_logo_image_big"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="color_gradient_1",
            field=models.CharField(blank=True, default="#FF4D79", max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="color_gradient_2",
            field=models.CharField(blank=True, default="#FF809F", max_length=250),
        ),
    ]
