# Generated by Django 4.1.7 on 2023-02-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_homepage_color_gradient_1_homepage_color_gradient_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="color_primary",
            field=models.CharField(blank=True, default="#ff4a67", max_length=250),
        ),
    ]
