# Generated by Django 4.1.7 on 2023-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_alter_segmentpage_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="message_show_time",
            field=models.CharField(
                blank=True, default="Próximamente...", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_time",
            field=models.BooleanField(default=True),
        ),
    ]
