# Generated by Django 4.1.7 on 2023-04-22 00:34

from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_alter_segmentpage_segments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentpage",
            name="segments",
            field=wagtail.fields.StreamField(
                [
                    (
                        "detail_segment",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        blank=False, max_length=250
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "list_options",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.RichTextBlock(required=False)
                                    ),
                                ),
                                ("url", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "url_text",
                                    wagtail.blocks.CharBlock(
                                        default="More info",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "position",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Izquierda"),
                                            ("right", "Derecha"),
                                            ("full", "Completa"),
                                            ("empty", "Sin Imagen"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_segment",
                        wagtail.blocks.StructBlock(
                            [("url", wagtail.blocks.URLBlock(blank=True))]
                        ),
                    ),
                    (
                        "information_segment",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "id_tag",
                                    wagtail.blocks.CharBlock(
                                        default="contact-text",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "class_name",
                                    wagtail.blocks.CharBlock(
                                        default="contact-wrapper",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "list_information",
                                    wagtail.blocks.ListBlock(
                                        home.models.InformationBlock, max_num=4
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "sponsor_segment",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        default="Sponsors",
                                        max_length=250,
                                        required=True,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "background",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "sponsors",
                                    wagtail.blocks.ListBlock(home.models.SponsorBlock),
                                ),
                            ]
                        ),
                    ),
                    (
                        "maps_segment",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        blank=True,
                                        help_text="https://www.google.com/maps/embed?pb=.....",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "pricing_segment",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        default="Pricing", max_length=250, required=True
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "tiers",
                                    wagtail.blocks.ListBlock(home.models.TiersBlock),
                                ),
                            ]
                        ),
                    ),
                    (
                        "schedule_segment",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        default="Schedule",
                                        max_length=250,
                                        required=True,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "schedules",
                                    wagtail.blocks.ListBlock(home.models.ScheduleBlock),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=False,
            ),
        ),
    ]
