# Generated by Django 4.1.7 on 2023-09-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_alter_homepage_footer_networks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_image_overlay_opacity",
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
        ),
    ]
