# Generated by Django 4.1.7 on 2023-09-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_homepage_hero_image_overlay_opacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="position_event",
            field=models.CharField(
                choices=[("center", "center"), ("left", "left"), ("right", "right")],
                default="center",
                max_length=250,
            ),
        ),
    ]
