# Generated by Django 4.1.7 on 2023-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_alter_homepage_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="color_text_hero",
            field=models.CharField(blank=True, default="#FFFFFF", max_length=250),
        ),
    ]
