# Generated by Django 4.1.7 on 2023-09-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_segmentpage_background_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background_section",
            field=models.CharField(blank=True, default="#FFFFFF", max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="color_text_section",
            field=models.CharField(blank=True, default="white", max_length=250),
        ),
    ]
