# Generated by Django 4.1.7 on 2023-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_homepage_background_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="navbar_background",
            field=models.CharField(default="transparent", max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="navbar_links_color",
            field=models.CharField(default="white", max_length=250),
        ),
    ]
