# Generated by Django 4.1.11 on 2023-10-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0038_homepage_navbar_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="max size 256x256 png format",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
