# Generated by Django 4.1.11 on 2023-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_homepage_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="footer_background",
            field=models.CharField(blank=True, default="#161E26", max_length=250),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_color_text",
            field=models.CharField(blank=True, default="#9e9e9e", max_length=250),
        ),
    ]
