# Generated by Django 4.1.11 on 2023-10-01 23:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_homepage_footer_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="externalRaws",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external",
                        wagtail.blocks.StructBlock(
                            [("rawHTML", wagtail.blocks.RawHTMLBlock(required=False))]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
