# Generated by Django 5.0.9 on 2024-09-08 22:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_homepage_externalraws'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='fonts',
            field=wagtail.fields.StreamField([('fonts', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': '#000000', 'max_length': 250, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('section', 0), ('url', 1), ('font_size', 0), ('font_wight', 0), ('font_family', 0), ('font_color', 2)]], {})}),
        ),
    ]
