# Generated by Django 5.0.9 on 2024-09-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_homepage_fonts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='fonts',
        ),
        migrations.AddField(
            model_name='homepage',
            name='primaryFontFamily',
            field=models.CharField(default='sans-serif', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primaryFontURL',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondaryFontFamily',
            field=models.CharField(default='sans-serif', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondaryFontURL',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
