# Generated by Django 5.0.9 on 2024-10-03 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_alter_homepage_background_section_and_more"),
        ("home", "0043_remove_homepage_fonts_homepage_primaryfontfamily_and_more"),
    ]

    operations = []
