# Generated by Django 5.0.9 on 2024-11-09 00:21

import home.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0044_merge_20241002_2210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentpage",
            name="segments",
            field=wagtail.fields.StreamField(
                [
                    ("detail_segment", 8),
                    ("video_segment", 10),
                    ("information_segment", 14),
                    ("sponsor_segment", 17),
                    ("maps_segment", 19),
                    ("pricing_segment", 22),
                    ("schedule_segment", 25),
                    ("iframe_segment", 27),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": False, "max_length": 250},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: ("wagtail.blocks.ListBlock", (1,), {}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "More info", "max_length": 250, "required": False},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Izquierda"),
                                ("right", "Derecha"),
                                ("full", "Completa"),
                                ("empty", "Sin Imagen"),
                            ]
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 0),
                                ("description", 1),
                                ("list_options", 2),
                                ("url", 3),
                                ("url_text", 4),
                                ("image", 5),
                                ("position", 6),
                                ("list_style", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.URLBlock", (), {"blank": True}),
                    10: ("wagtail.blocks.StructBlock", [[("url", 9)]], {}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "contact-text",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "contact-wrapper",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (home.models.InformationBlock,),
                        {"max_num": 4},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("id_tag", 11),
                                ("class_name", 12),
                                ("list_information", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sponsors", "max_length": 250, "required": True},
                    ),
                    16: ("wagtail.blocks.ListBlock", (home.models.SponsorBlock,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 15),
                                ("description", 1),
                                ("background", 5),
                                ("sponsors", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "https://www.google.com/maps/embed?pb=.....",
                        },
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("url", 18)]], {}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 250, "required": True},
                    ),
                    21: ("wagtail.blocks.ListBlock", (home.models.TiersBlock,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 20), ("description", 1), ("tiers", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Schedule", "max_length": 250, "required": True},
                    ),
                    24: ("wagtail.blocks.ListBlock", (home.models.ScheduleBlock,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 23), ("description", 1), ("schedules", 24)]],
                        {},
                    ),
                    26: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    27: ("wagtail.blocks.StructBlock", [[("rawHTML", 26)]], {}),
                },
            ),
        ),
    ]
